### ISSUE TITLE
export_schema NoClassDefFoundError on cassaforte 2.0

### ISSUE THREAD

**Issue by Keksike** [clojurewerkz/cassaforte#120]
Hi, 

I'm getting this kind of error with cassandra & cassaforte 2.0.

```
Exception in thread "main" java.lang.NoClassDefFoundError: clojurewerkz/cassaforte/client$export_schema
        at clojurewerkz.cassaforte.client__init.load(Unknown Source)
        at clojurewerkz.cassaforte.client__init.<clinit>(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:344)
        at clojure.lang.RT.loadClassForName(RT.java:2093)
        at clojure.lang.RT.load(RT.java:430)
        at clojure.lang.RT.load(RT.java:411)
        at clojure.core$load$fn__5066.invoke(core.clj:5641)
        at clojure.core$load.doInvoke(core.clj:5640)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invoke(core.clj:5446)
        at clojure.core$load_lib$fn__5015.invoke(core.clj:5486)
        at clojure.core$load_lib.doInvoke(core.clj:5485)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invoke(core.clj:626)
        at clojure.core$load_libs.doInvoke(core.clj:5524)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invoke(core.clj:626)
        at clojure.core$require.doInvoke(core.clj:5607)
        at clojure.lang.RestFn.invoke(RestFn.java:436)
        at clojurewerkz.cassaforte.cql$loading__4958__auto__.invoke(cql.clj:10)
        at clojurewerkz.cassaforte.cql__init.load(Unknown Source)
        at clojurewerkz.cassaforte.cql__init.<clinit>(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:344)
        at clojure.lang.RT.loadClassForName(RT.java:2093)
        at clojure.lang.RT.load(RT.java:430)
        at clojure.lang.RT.load(RT.java:411)
        at clojure.core$load$fn__5066.invoke(core.clj:5641)
        at clojure.core$load.doInvoke(core.clj:5640)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invoke(core.clj:5446)
        at clojure.core$load_lib$fn__5015.invoke(core.clj:5486)
        at clojure.core$load_lib.doInvoke(core.clj:5485)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invoke(core.clj:626)
```

The error-message doesn't really tell me much. Any idea?

**Comment by michaelklishin** [comment]
It says that the `clojurewerkz.cassaforte.client/export_schema` function isn't found. [It does exist](https://github.com/clojurewerkz/cassaforte/blame/master/src/clojure/clojurewerkz/cassaforte/client.clj#L293), has been around since mid-2013 and is public.

**Comment by Keksike** [comment]
What is the solution to fix the problem? I'm not even calling the export_schema function anywhere AFAIK.

**Comment by michaelklishin** [comment]
I'm pretty sure Cassaforte itself doesn't use it internally either. First thing I'd check is whether you have multiple Cassaforte versions on your classpath, e.g. due to transitive dependencies. `lein deps :tree` makes it easy to see.

**Comment by Keksike** [comment]
We only have one Cassaforte version in the classpath, `[clojurewerkz/cassaforte "2.0.0-rc4"]`.

**Comment by michaelklishin** [comment]
Then first course of action is to move to a non-RC version.

**Comment by Keksike** [comment]
I changed to 2.0.0, didn't fix the problem.

Cassandra version was 2.0.12 actually, not 2.0.0 like I said in the first post.

**Comment by ifesdjeen** [comment]
@Keksike hey, sorry for confusion, but could you please try `[clojurewerkz/cassaforte "2.0.2"]` version? 

It's very confusing since these artifacts are almost a year old and theyve always worked, so I'm extremely surprised they suddenly stop working...
